/** @type {import('prettier').Config} */
module.exports = {
	endOfLine: "lf",
	useTabs: true,
	semi: true,
	singleQuote: false,
	printWidth: 120,
	importOrder: [
		"^(react/(.*)$)|^(react$)",
		"^(next/(.*)$)|^(next$)",
		"<THIRD_PARTY_MODULES>",
		"",
		"^types$",
		"^@/types/(.*)$",
		"^@/config/(.*)$",
		"^@/lib/(.*)$",
		"^@/components/(.*)$",
		"^@/styles/(.*)$",
		"^[./]",
	],
	importOrderSeparation: false,
	importOrderSortSpecifiers: true,
	importOrderBuiltinModulesToTop: true,
	importOrderParserPlugins: ["typescript", "jsx", "decorators-legacy"],
	importOrderMergeDuplicateImports: true,
	importOrderCombineTypeAndValueImports: true,
	plugins: ["@ianvs/prettier-plugin-sort-imports"],
};
